# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-web:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: npm run build --if-present
  run-api:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: pm2 restart api
