# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install deps for api
      run: yarn install
      working-directory: ./api
    - name: Restart api
      run: pm2 restart api
      working-directory: ./api
    - name: Install deps for web
      run: yarn install
      working-directory: ./web
    - name: Build web
      run: npm run build --if-present
      working-directory: ./web
